plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.mapconductor.webviewleaflet.example"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.mapconductor.sample.webviewleaflet"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
    }

    buildFeatures {
        compose = true
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(libs.mapconductor.webview.leaflet)
    implementation(libs.mapconductor.core)

    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.foundation)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    debugImplementation(platform(libs.androidx.compose.bom))
    debugImplementation(libs.androidx.ui.tooling)
}

// The app's own custom page (react-for-leaflet + @mapconductor/webview-bridge, see
// ../webpage/README.md) is source, not the compiled JS under src/main/assets/leaflet — that
// directory is entirely generated by these tasks so nobody has to hand-copy npm build output
// (or wonder where it came from) after editing webpage/src.
val webpageDir = File(rootDir, "webpage")
val npmExecutable = if (System.getProperty("os.name").lowercase().contains("win")) "npm.cmd" else "npm"

val installWebpageDependencies by tasks.registering(Exec::class) {
    description = "npm install for the app's own custom webpage (see ../webpage/README.md)"
    workingDir = webpageDir
    commandLine(npmExecutable, "install")
    inputs.file(File(webpageDir, "package.json"))
    inputs.file(File(webpageDir, "package-lock.json"))
    outputs.dir(File(webpageDir, "node_modules"))
}

val buildWebpage by tasks.registering(Exec::class) {
    description = "Builds the app's own custom webpage via Vite (react-for-leaflet + webview-bridge)"
    dependsOn(installWebpageDependencies)
    workingDir = webpageDir
    commandLine(npmExecutable, "run", "build")
    inputs.dir(File(webpageDir, "src"))
    inputs.file(File(webpageDir, "index.html"))
    inputs.file(File(webpageDir, "vite.config.ts"))
    inputs.file(File(webpageDir, "tsconfig.json"))
    outputs.dir(File(webpageDir, "dist"))
}

val copyWebpageAssets by tasks.registering(Copy::class) {
    description = "Copies the built webpage into src/main/assets/leaflet"
    dependsOn(buildWebpage)
    // Vite's output filenames are content-hashed, so a plain Copy would leave every previous
    // build's now-orphaned index-<oldhash>.js/.css sitting alongside the current one instead of
    // replacing it — wipe the destination first so it always mirrors dist/ exactly.
    doFirst {
        delete(file("src/main/assets/leaflet"))
    }
    from(File(webpageDir, "dist")) {
        exclude("**/*.map")
    }
    into(file("src/main/assets/leaflet"))
}

tasks.named("preBuild") {
    dependsOn(copyWebpageAssets)
}
